# Generated by Django 3.0.7 on 2020-10-12 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
