# Generated by Django 3.0.7 on 2020-07-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='difficulty',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
