# Generated by Django 3.0.7 on 2020-07-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='practice',
            name='subdomain',
            field=models.ManyToManyField(to='adminpanel.SubDomain'),
        ),
    ]
