# Generated by Django 3.0.7 on 2020-07-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_practice_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='description',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
