# Generated by Django 3.0.5 on 2020-04-21 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20200417_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Track')),
            ],
        ),
    ]
