# Generated by Django 3.0.8 on 2020-07-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_practice_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='practice',
            name='subdomain',
            field=models.ManyToManyField(to='adminpanel.SubDomain'),
        ),
    ]
