# Generated by Django 3.0.6 on 2020-05-29 06:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
