# Generated by Django 3.0.7 on 2020-07-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20200715_1459'),
        ('adminpanel', '0005_practice_slug'),
    ]

    operations = [
    ]
