# Generated by Django 3.0.7 on 2020-07-20 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_merge_20200719_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={},
        ),
        migrations.AlterField(
            model_name='practice',
            name='description',
            field=models.TextField(default='Description is coming', max_length=50),
        ),
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(default=uuid.UUID('dc5307f1-9967-40cc-a5b6-802b43d88de1'), max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0b2cd07d-79e8-4740-b8dc-38eb654b8b29'), max_length=250),
        ),
    ]
