# Generated by Django 3.0.7 on 2020-07-21 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_merge_20200719_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={},
        ),
        migrations.AlterField(
            model_name='practice',
            name='description',
            field=models.TextField(default='Description is coming', max_length=50),
        ),
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0b64eb0b-8676-46e1-9a61-688758a9a50d'), max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2d1985e5-ccd1-4d52-ba52-28e458e25db6'), max_length=250),
        ),
    ]
