# Generated by Django 3.0.7 on 2020-07-29 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20200720_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3c935bbd-5b63-43f2-ae5b-639502952f07'), max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=uuid.UUID('63c1ce9e-a1ec-4cf5-b164-ab5379caa044'), max_length=250),
        ),
    ]
