# Generated by Django 3.0.7 on 2020-07-22 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20200721_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(default=uuid.UUID('cdb3a908-fad7-4cd5-bcbd-7af41c20d1a4'), max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=uuid.UUID('66aeb720-bd99-446d-9f2b-97b4d68fef87'), max_length=250),
        ),
    ]
