# Generated by Django 3.0.7 on 2020-09-05 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_auto_20200729_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='difficulty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(default=uuid.UUID('cacd3c90-cdcb-45f7-980c-356e170f0ad7'), max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=uuid.UUID('eaa0239d-f0b1-4c38-bf4f-9a5a901c66c7'), max_length=250),
        ),
    ]
