# Generated by Django 3.0.7 on 2020-07-23 05:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_auto_20200722_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(default=uuid.UUID('de901b0a-3527-4b2f-a8de-1089e498b439'), max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a009e92e-295a-430a-80c8-451811b7d97f'), max_length=250),
        ),
    ]
