# Generated by Django 3.0.7 on 2020-09-25 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_auto_20200905_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(default=uuid.UUID('567a7a0c-6e76-4d2e-a21d-385d7f8b891d'), max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a2872f68-55aa-4247-933b-e01a9fec5581'), max_length=250),
        ),
    ]
