# Generated by Django 3.0.7 on 2020-07-27 03:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_auto_20200723_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(default=uuid.UUID('12d59ee0-a12c-49a8-ac4e-6cb9e6876250'), max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=uuid.UUID('18592ae9-ba59-49e1-8dea-3cd91271ae59'), max_length=250),
        ),
    ]
