# Generated by Django 3.0.7 on 2020-07-27 04:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_auto_20200727_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f499ac2e-f3fc-42fd-99a1-1901ed39bebf'), max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=uuid.UUID('03ea75aa-6f0c-4d95-8429-daa8766d2810'), max_length=250),
        ),
    ]
