# Generated by Django 3.0.7 on 2020-07-29 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_auto_20200727_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fe291c39-fd2b-43ce-88c3-83c7dbfb1ccb'), max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5423f680-5f2f-41c8-b6a7-f2382b8fc989'), max_length=250),
        ),
    ]
