# Generated by Django 3.0.7 on 2020-08-31 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_auto_20200729_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f2063e9d-238a-44ee-8e58-6182fcda3fdd'), max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=uuid.UUID('39f9752a-11b2-43ed-aef9-9b0f662c74e7'), max_length=250),
        ),
    ]
