# Generated by Django 3.0.7 on 2020-08-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_auto_20200729_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
