# Generated by Django 3.0.7 on 2020-08-31 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_auto_20200831_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c0cc38b1-6551-43fa-beb7-4bb6186b0236'), max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5dbe8eb4-e015-4cdd-be37-8370c209660c'), max_length=250),
        ),
    ]
