# Generated by Django 3.0.7 on 2020-08-31 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_auto_20200831_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(default=uuid.UUID('aebf25b8-27db-4128-a6a1-76f6acea6e9d'), max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a584079d-ca7c-4fbc-a9f6-410e4816aa62'), max_length=250),
        ),
    ]
