# Generated by Django 3.0.7 on 2020-09-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_auto_20200831_2034'),
        ('adminpanel', '0014_auto_20200823_0248'),
    ]

    operations = [
    ]
