# Generated by Django 3.0.7 on 2020-09-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_merge_20200901_1051'),
        ('adminpanel', '0014_auto_20200809_2051'),
        ('adminpanel', '0009_auto_20200905_1330'),
    ]

    operations = [
    ]
