# Generated by Django 3.0.5 on 2020-05-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0003_auto_20200428_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='works_at',
        ),
    ]
