# Generated by Django 3.0.7 on 2020-06-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0005_auto_20200528_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
