# Generated by Django 3.0.7 on 2020-09-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0008_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('xs', '1-10'), ('sm', '11-50'), ('md', '51-150'), ('lg', '151-300'), ('xl', '300+')], max_length=50, null=True),
        ),
    ]
