# Generated by Django 3.0.7 on 2020-10-18 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='subdomain',
            field=models.ManyToManyField(related_name='subdomain', to='practice.Subdomain'),
        ),
        migrations.CreateModel(
            name='PracticeSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.Practice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='practice',
            name='solutions',
            field=models.ManyToManyField(related_name='solutions', through='practice.PracticeSolution', to=settings.AUTH_USER_MODEL),
        ),
    ]
