# Generated by Django 3.0.7 on 2020-07-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='subdomain',
            field=models.ManyToManyField(to='challenge.Subdomain'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='guidelines',
            field=models.TextField(blank=True),
        ),
    ]
