# Generated by Django 3.0.7 on 2020-09-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesparticipation',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengesparticipation',
            name='submission_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
