# Generated by Django 3.0.7 on 2020-07-22 13:31

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20200721_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='body',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
