# Generated by Django 3.0.7 on 2020-10-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_remove_challengesparticipation_finished'),
        ('challenge', '0002_auto_20201002_2322'),
    ]

    operations = [
    ]
