# Generated by Django 3.0.7 on 2020-07-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_challenge_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
