# Generated by Django 3.0.7 on 2020-09-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200908_2049'),
        ('job', '0002_auto_20200907_1436'),
    ]

    operations = [
    ]
